export const INDUSTRIES = [
  "Plumbing",
  "Heating & Air Conditioning (HVAC)",
  "Electrical",
  "Handyman",
  "General Contractor",
  "Home Cleaning",
  "Carpet Cleaning",
  "Landscaping & Lawn",
  "Appliances",
  "Pest Control",
  "Window & Exterior Cleaning",
  "Automotive",
  "Other",
] as const;

export type Industry = typeof INDUSTRIES[number];

export interface PresetItem {
  name: string;
  description?: string;
  defaultPriceCents: number;
  unit: string;
  category: string;
}

export const INDUSTRY_PRESETS: Record<string, PresetItem[]> = {
  "Plumbing": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Drain Cleaning", defaultPriceCents: 0, unit: "job", category: "Drain" },
    { name: "Toilet Repair", defaultPriceCents: 0, unit: "job", category: "Fixtures" },
    { name: "Toilet Replacement", defaultPriceCents: 0, unit: "job", category: "Fixtures" },
    { name: "Faucet Repair", defaultPriceCents: 0, unit: "job", category: "Fixtures" },
    { name: "Faucet Replacement", defaultPriceCents: 0, unit: "job", category: "Fixtures" },
    { name: "Water Heater Install", defaultPriceCents: 0, unit: "job", category: "Water Heater" },
    { name: "Water Heater Repair", defaultPriceCents: 0, unit: "job", category: "Water Heater" },
    { name: "Leak Detection", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Pipe Repair", defaultPriceCents: 0, unit: "job", category: "Pipes" },
    { name: "Garbage Disposal Install", defaultPriceCents: 0, unit: "job", category: "Fixtures" },
  ],
  "Heating & Air Conditioning (HVAC)": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "AC Tune-up", defaultPriceCents: 0, unit: "job", category: "Maintenance" },
    { name: "Heating Tune-up", defaultPriceCents: 0, unit: "job", category: "Maintenance" },
    { name: "Filter Replacement", defaultPriceCents: 0, unit: "each", category: "Maintenance" },
    { name: "Thermostat Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Duct Cleaning", defaultPriceCents: 0, unit: "job", category: "Maintenance" },
    { name: "AC Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Furnace Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "AC Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Furnace Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Refrigerant Recharge", defaultPriceCents: 0, unit: "job", category: "Repair" },
  ],
  "Electrical": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Outlet Install", defaultPriceCents: 0, unit: "each", category: "Install" },
    { name: "Outlet Repair", defaultPriceCents: 0, unit: "each", category: "Repair" },
    { name: "Switch Install", defaultPriceCents: 0, unit: "each", category: "Install" },
    { name: "Light Fixture Install", defaultPriceCents: 0, unit: "each", category: "Install" },
    { name: "Ceiling Fan Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Panel Upgrade", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Circuit Breaker Replacement", defaultPriceCents: 0, unit: "each", category: "Repair" },
    { name: "Wiring Repair", defaultPriceCents: 0, unit: "hour", category: "Repair" },
    { name: "EV Charger Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Whole House Surge Protector", defaultPriceCents: 0, unit: "job", category: "Install" },
  ],
  "Handyman": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Hourly Labor", defaultPriceCents: 0, unit: "hour", category: "Labor" },
    { name: "Drywall Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Door Install", defaultPriceCents: 0, unit: "each", category: "Install" },
    { name: "Door Repair", defaultPriceCents: 0, unit: "each", category: "Repair" },
    { name: "Furniture Assembly", defaultPriceCents: 0, unit: "job", category: "Assembly" },
    { name: "TV Mounting", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Shelving Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Painting", defaultPriceCents: 0, unit: "sq_ft", category: "Paint" },
    { name: "Pressure Washing", defaultPriceCents: 0, unit: "hour", category: "Cleaning" },
    { name: "Gutter Cleaning", defaultPriceCents: 0, unit: "job", category: "Cleaning" },
    { name: "Caulking", defaultPriceCents: 0, unit: "job", category: "Repair" },
  ],
  "General Contractor": [
    { name: "Consultation", defaultPriceCents: 0, unit: "hour", category: "General" },
    { name: "Project Management", defaultPriceCents: 0, unit: "day", category: "General" },
    { name: "Demolition", defaultPriceCents: 0, unit: "job", category: "Demo" },
    { name: "Framing", defaultPriceCents: 0, unit: "sq_ft", category: "Construction" },
    { name: "Drywall Install", defaultPriceCents: 0, unit: "sq_ft", category: "Construction" },
    { name: "Flooring Install", defaultPriceCents: 0, unit: "sq_ft", category: "Flooring" },
    { name: "Tile Install", defaultPriceCents: 0, unit: "sq_ft", category: "Flooring" },
    { name: "Cabinet Install", defaultPriceCents: 0, unit: "job", category: "Kitchen" },
    { name: "Countertop Install", defaultPriceCents: 0, unit: "job", category: "Kitchen" },
    { name: "Trim Work", defaultPriceCents: 0, unit: "ft", category: "Finish" },
    { name: "Painting", defaultPriceCents: 0, unit: "sq_ft", category: "Paint" },
    { name: "Permit Fee", defaultPriceCents: 0, unit: "job", category: "Permits" },
  ],
  "Home Cleaning": [
    { name: "Standard Cleaning", defaultPriceCents: 0, unit: "job", category: "Cleaning" },
    { name: "Deep Cleaning", defaultPriceCents: 0, unit: "job", category: "Cleaning" },
    { name: "Move-in/Move-out Cleaning", defaultPriceCents: 0, unit: "job", category: "Cleaning" },
    { name: "Hourly Cleaning", defaultPriceCents: 0, unit: "hour", category: "Cleaning" },
    { name: "Window Cleaning (Interior)", defaultPriceCents: 0, unit: "job", category: "Windows" },
    { name: "Oven Cleaning", defaultPriceCents: 0, unit: "each", category: "Appliance" },
    { name: "Refrigerator Cleaning", defaultPriceCents: 0, unit: "each", category: "Appliance" },
    { name: "Laundry Service", defaultPriceCents: 0, unit: "job", category: "Laundry" },
    { name: "Organization Service", defaultPriceCents: 0, unit: "hour", category: "Organization" },
    { name: "Post-Construction Cleaning", defaultPriceCents: 0, unit: "job", category: "Cleaning" },
  ],
  "Carpet Cleaning": [
    { name: "Carpet Cleaning (per room)", defaultPriceCents: 0, unit: "each", category: "Carpet" },
    { name: "Carpet Cleaning (per sq ft)", defaultPriceCents: 0, unit: "sq_ft", category: "Carpet" },
    { name: "Stain Treatment", defaultPriceCents: 0, unit: "each", category: "Treatment" },
    { name: "Pet Odor Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Scotchgard Protection", defaultPriceCents: 0, unit: "sq_ft", category: "Treatment" },
    { name: "Upholstery Cleaning", defaultPriceCents: 0, unit: "each", category: "Upholstery" },
    { name: "Area Rug Cleaning", defaultPriceCents: 0, unit: "each", category: "Rugs" },
    { name: "Tile & Grout Cleaning", defaultPriceCents: 0, unit: "sq_ft", category: "Tile" },
    { name: "Stairs Cleaning", defaultPriceCents: 0, unit: "each", category: "Carpet" },
    { name: "Hallway Cleaning", defaultPriceCents: 0, unit: "each", category: "Carpet" },
  ],
  "Landscaping & Lawn": [
    { name: "Lawn Mowing", defaultPriceCents: 0, unit: "job", category: "Lawn Care" },
    { name: "Edging", defaultPriceCents: 0, unit: "job", category: "Lawn Care" },
    { name: "Trimming/Weed Eating", defaultPriceCents: 0, unit: "job", category: "Lawn Care" },
    { name: "Leaf Removal", defaultPriceCents: 0, unit: "job", category: "Cleanup" },
    { name: "Mulching", defaultPriceCents: 0, unit: "job", category: "Landscape" },
    { name: "Shrub Trimming", defaultPriceCents: 0, unit: "job", category: "Landscape" },
    { name: "Tree Trimming", defaultPriceCents: 0, unit: "job", category: "Trees" },
    { name: "Planting", defaultPriceCents: 0, unit: "hour", category: "Landscape" },
    { name: "Irrigation Repair", defaultPriceCents: 0, unit: "job", category: "Irrigation" },
    { name: "Fertilization", defaultPriceCents: 0, unit: "job", category: "Lawn Care" },
    { name: "Weed Control", defaultPriceCents: 0, unit: "job", category: "Lawn Care" },
    { name: "Sod Installation", defaultPriceCents: 0, unit: "sq_ft", category: "Lawn Care" },
  ],
  "Appliances": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Refrigerator Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Washer Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Dryer Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Dishwasher Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Oven/Range Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Microwave Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Garbage Disposal Repair", defaultPriceCents: 0, unit: "job", category: "Repair" },
    { name: "Appliance Install", defaultPriceCents: 0, unit: "job", category: "Install" },
    { name: "Parts", defaultPriceCents: 0, unit: "each", category: "Parts" },
    { name: "Hourly Labor", defaultPriceCents: 0, unit: "hour", category: "Labor" },
  ],
  "Pest Control": [
    { name: "Initial Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Monthly Service", defaultPriceCents: 0, unit: "job", category: "Service" },
    { name: "Quarterly Service", defaultPriceCents: 0, unit: "job", category: "Service" },
    { name: "Ant Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Roach Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Rodent Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Termite Inspection", defaultPriceCents: 0, unit: "job", category: "Inspection" },
    { name: "Termite Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Bed Bug Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Mosquito Treatment", defaultPriceCents: 0, unit: "job", category: "Treatment" },
    { name: "Wildlife Removal", defaultPriceCents: 0, unit: "job", category: "Removal" },
    { name: "Exclusion Work", defaultPriceCents: 0, unit: "job", category: "Prevention" },
  ],
  "Window & Exterior Cleaning": [
    { name: "Window Cleaning (per window)", defaultPriceCents: 0, unit: "each", category: "Windows" },
    { name: "Window Cleaning (whole house)", defaultPriceCents: 0, unit: "job", category: "Windows" },
    { name: "Screen Cleaning", defaultPriceCents: 0, unit: "each", category: "Windows" },
    { name: "Pressure Washing (driveway)", defaultPriceCents: 0, unit: "job", category: "Pressure Wash" },
    { name: "Pressure Washing (deck)", defaultPriceCents: 0, unit: "job", category: "Pressure Wash" },
    { name: "Pressure Washing (siding)", defaultPriceCents: 0, unit: "job", category: "Pressure Wash" },
    { name: "Gutter Cleaning", defaultPriceCents: 0, unit: "job", category: "Gutters" },
    { name: "Gutter Guard Install", defaultPriceCents: 0, unit: "ft", category: "Gutters" },
    { name: "Roof Cleaning", defaultPriceCents: 0, unit: "job", category: "Roof" },
    { name: "Solar Panel Cleaning", defaultPriceCents: 0, unit: "job", category: "Solar" },
  ],
  "Automotive": [
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Oil Change", defaultPriceCents: 0, unit: "job", category: "Maintenance" },
    { name: "Tire Rotation", defaultPriceCents: 0, unit: "job", category: "Tires" },
    { name: "Tire Replacement", defaultPriceCents: 0, unit: "each", category: "Tires" },
    { name: "Brake Pad Replacement", defaultPriceCents: 0, unit: "job", category: "Brakes" },
    { name: "Brake Rotor Replacement", defaultPriceCents: 0, unit: "each", category: "Brakes" },
    { name: "Battery Replacement", defaultPriceCents: 0, unit: "job", category: "Electrical" },
    { name: "Alignment", defaultPriceCents: 0, unit: "job", category: "Suspension" },
    { name: "AC Recharge", defaultPriceCents: 0, unit: "job", category: "AC" },
    { name: "Hourly Labor", defaultPriceCents: 0, unit: "hour", category: "Labor" },
    { name: "Parts", defaultPriceCents: 0, unit: "each", category: "Parts" },
    { name: "Towing", defaultPriceCents: 0, unit: "job", category: "Towing" },
  ],
  "Other": [
    { name: "Service Call", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Diagnostic", defaultPriceCents: 0, unit: "job", category: "General" },
    { name: "Hourly Labor", defaultPriceCents: 0, unit: "hour", category: "Labor" },
    { name: "Materials", defaultPriceCents: 0, unit: "each", category: "Materials" },
    { name: "Travel Fee", defaultPriceCents: 0, unit: "job", category: "Travel" },
  ],
};
